name = "caseonix-status"
main = "src/index.ts"
compatibility_date = "2026-04-01"
workers_dev = false

[[kv_namespaces]]
binding = "STATUS_KV"
id = "9ec894c7ddf3411791315e3b43d6774d"

[[routes]]
pattern = "caseonix.ca/api/*"
zone_name = "caseonix.ca"

[[routes]]
pattern = "caseonix.ca/webhooks/*"
zone_name = "caseonix.ca"
